name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      PACKAGE_NAME: Injection
      
    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@v1
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v2
    - name: Prepare Build
      run: brew bundle
    - name: Build
      run: swift build
    - name: Lint
      if: startsWith(github.ref, 'refs/tags/') != true
      run: swiftformat --lint . && swiftlint
    - name: Run tests
      run: swift test --enable-code-coverage
#    - name: Prepare Code Coverage
#      run: xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name ${{ env.PACKAGE_NAME }}PackageTests) > info.lcov
#    - name: Upload to CodeCov.io
#      uses: codecov/codecov-action@v2
#      with:
#        files: ./info.lcov
